# Be explicit: Tell CloudCannon the source and output are the same root directory.
source: .
output_path: .

# Find all HTML files in the root and treat them as site pages.
collections_config:
  pages:
    path: .
    output: true
    glob: ["*.html"]
